### ISSUE TITLE
[Question]  - How do I keep grunt-ngrok alive?

### ISSUE THREAD

**Issue by c990802** [bazilio91/grunt-ngrok#3]
I am running ```grunt ngrok:server``` with a configuration similar to the one at your README, and the process finishes right away. Is there a way to keep the process alive, without depending on other modules?

**Comment by bazilio91** [comment]
You can create an empty grunt task, with `this.async();` in it, and keep grunt process alive. Does this hack solve your problem?

**Comment by c990802** [comment]
Yes, this does make the trick.
thanks!
