### ISSUE TITLE
Update to ngrok v2

### ISSUE THREAD

**Issue by elchiconube** [bazilio91/grunt-ngrok#4]
Hi! I want to use this module but it's necessary an update ¿Anyone can help me or maybe change to gulp?

Thanks a lot

**Comment by bazilio91** [comment]
https://github.com/bubenshchykov/ngrok supports ngrok v2, and it should be easy to integrate with grunt or upgrade this plugin. Feel free to make PR.

**Comment by elchiconube** [comment]
Thanks @bazilio91 I'll try

**Comment by elchiconube** [comment]
Sorry but I'm trying to update this and I can't. I never do a grunt plugin and for me it's impossible. Can you please update it? Thanks a lot @bazilio91

**Comment by gabeharms** [comment]
Done
